# Generated by Django 5.0.7 on 2024-07-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_profile_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='quantity',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
    ]
