# Generated by Django 5.0.7 on 2024-07-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_foods_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='price',
        ),
    ]
