# Generated by Django 5.0.7 on 2024-07-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_remove_foods_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='quantity',
        ),
        migrations.AddField(
            model_name='foods',
            name='price',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
    ]
